/**
 * Frontend type contract.
 *
 * Pydantic-derived shapes come from `./generated.ts` (regenerated by
 * `./Quickstart gen-types`). The exports below are a thin shim — most
 * are direct re-exports; the remainder widen the generated types with
 * frontend-only concerns (the `'datasheet'` view type, the filter UI's
 * tri-state ProductType).
 *
 * **Don't hand-edit shapes here that exist in `generated.ts`.** If a
 * shape looks wrong, fix the Pydantic source under `specodex/models/`
 * and re-run `./Quickstart gen-types`. CI's `test-codegen` job blocks
 * deploys on drift.
 *
 * MODELGEN.md Phase 0a-ii — closes the hand-typed mirror.
 */

// Direct re-exports — interfaces and primitive shape types from Pydantic.
export type {
  ValueUnit,
  MinMaxUnit,
  Dimensions,
  Motor,
  Drive,
  Gearhead,
  RobotArm,
  Contactor,
  ContactorPowerRating,
  ContactorIcwRating,
  ElectricCylinder,
  LinearActuator,
  Manufacturer,
  Datasheet,
  ProductBase,
} from './generated';
export { PRODUCT_TYPES } from './generated';
import type {
  Product as GeneratedProduct,
  ProductTypeLiteral,
} from './generated';

/**
 * Tighten a generated discriminated-union member so `product_id` and
 * `product_type` are required.
 *
 * Pydantic emits both as optional in the JSON schema (`product_id` has
 * `default_factory=uuid4`; `product_type` has a literal default like
 * `"motor"`), so the generated TS marks them `?`. But every product the
 * **frontend** ever sees has been persisted to DynamoDB and read back —
 * both fields are guaranteed present at runtime. This transform keeps
 * the discriminated union intact (each member's `product_type` literal
 * stays its own narrow type) while removing the optionality.
 */
type Persisted<T> = T extends { product_type?: infer U }
  ? Omit<T, 'product_id' | 'product_type'> & {
      product_id: string;
      product_type: NonNullable<U>;
    }
  : never;

/**
 * Frontend view type for a datasheet record.
 *
 * Datasheets aren't a Pydantic `ProductBase` subclass (they live in
 * `specodex/models/datasheet.py:Datasheet`, separate from products),
 * so they're not part of the generated `Product` union. The frontend
 * still treats them as "a kind of product" for filter UI purposes —
 * this interface captures the fields the SPA reads on a datasheet row.
 *
 * Kept hand-typed because there is no clean Pydantic source to
 * regenerate from for this view: the shape mixes `Datasheet` fields
 * with derived frontend state (`is_scraped`).
 */
export interface DatasheetEntry {
  product_type: 'datasheet';
  /** Always present once the datasheet is in DynamoDB; matches Persisted<>. */
  product_id: string;
  product_name: string;
  manufacturer: string;
  /** The actual component type the datasheet describes ('motor', 'drive', …). */
  component_type?: string;
  product_family?: string;
  part_number?: string;
  url: string;
  pages?: number[];
  is_scraped?: boolean;
}

/**
 * The seven Pydantic product types plus `DatasheetEntry`.
 *
 * Discriminated by `product_type`:
 * - 'motor' | 'drive' | 'gearhead' | 'robot_arm' | 'contactor' |
 *   'electric_cylinder' | 'linear_actuator' → from generated.ts (each
 *   wrapped in `Persisted<>` so `product_id` and `product_type` are
 *   required, matching what the API actually returns)
 * - 'datasheet' → DatasheetEntry above
 */
export type Product = Persisted<GeneratedProduct> | DatasheetEntry;

/**
 * Filter UI's product-type selection state.
 *
 * Widens `ProductTypeLiteral` (the seven Pydantic product types) with:
 * - `'datasheet'` — the frontend view type for datasheet records
 * - `'all'` — no type filter applied
 * - `null` — no selection (initial state)
 */
export type ProductType = ProductTypeLiteral | 'datasheet' | 'all' | null;

/**
 * Product summary with dynamic counts per type.
 *
 * The backend returns counts for all product types dynamically, e.g.
 * `{ total: 10, motors: 5, drives: 3, robot_arms: 2 }`. Kept hand-typed
 * because it's a frontend-shaped view of the API response, not a
 * Pydantic model.
 */
export interface ProductSummary {
  total: number;
  [key: string]: number;
}
