# This module defines a base Pydantic model for tangible products, encapsulating
# common attributes that are shared across different types of hardware like drives,
# motors, etc. By creating a common base model, we ensure consistency,
# reduce code duplication, and improve maintainability of product-related models.

from __future__ import annotations

from typing import Any, Literal, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, BeforeValidator, Field
from typing_extensions import Annotated


from specodex.models.common import Mass, ProductType, ValueUnit
from specodex.placeholders import is_placeholder


def _coerce_placeholder_to_none(v: Any) -> Any:
    """Replace placeholder strings ("N/A", "TBD", ...) with None at ingest.

    Keeps the database free of "N/A" literals, which would otherwise inflate
    quality scores and render as garbage in the frontend table.
    """
    return None if is_placeholder(v) else v


PlaceholderSanitizedStr = Annotated[
    Optional[str],
    BeforeValidator(_coerce_placeholder_to_none),
]


class Dimensions(BaseModel):
    """Represents physical dimensions of an object."""

    width: Optional[float] = None
    length: Optional[float] = None
    height: Optional[float] = None
    unit: Optional[str] = "mm"


class ProductBase(BaseModel):
    """
    A base model for products with common attributes, designed for DynamoDB.

    This model uses a composite primary key (PK, SK) to align with DynamoDB's
    single-table design best practices.

    Attributes:
        PK: The Partition Key. Formatted as 'PRODUCT#<product_type>'.
        SK: The Sort Key. Formatted as 'PRODUCT#<product_id>'.
        product_id: The unique identifier (UUID) for the product.
    """

    model_config = {"populate_by_name": True}

    # PK/SK are persistence-layer concerns — kept as plain @property so they
    # don't appear in `model_dump()` or the generated TS interface, but are
    # still readable as attributes for the DynamoDB writer (see
    # specodex/db/dynamo.py:_serialize_item which assigns them explicitly).
    # Per MODELGEN.md OQ1 (resolved 2026-05-07): "drop the computed-field
    # decorator and compute PK/SK on read in the API."
    @property
    def PK(self) -> str:
        return f"PRODUCT#{self.product_type.upper()}"

    @property
    def SK(self) -> str:
        return f"PRODUCT#{self.product_id}"

    # AI-generated comment: product_id is auto-generated by the program, not by the LLM.
    # Making it Optional ensures the LLM won't try to create UUIDs, which it does incorrectly.
    # The default_factory ensures a UUID is always generated if not provided.
    product_id: UUID = Field(
        default_factory=uuid4, description="Unique identifier (auto-generated)"
    )
    product_type: ProductType = Field(
        ..., description="Type of product (e.g., 'motor', 'drive')"
    )
    product_name: str = Field(..., description="Product name")
    product_family: PlaceholderSanitizedStr = Field(
        None, description="Product family or sub-series"
    )
    part_number: PlaceholderSanitizedStr = Field(None, description="Part number")
    manufacturer: str = Field(..., description="Manufacturer name")
    release_year: Optional[int] = None
    dimensions: Optional[Dimensions] = None
    weight: Mass = None
    msrp: Optional[ValueUnit] = None
    msrp_source_url: Optional[str] = Field(
        None,
        description="URL the MSRP was scraped from. Populated by price-enrich.",
    )
    msrp_fetched_at: Optional[str] = Field(
        None, description="ISO 8601 timestamp when MSRP was last fetched."
    )
    availability: Optional[
        Literal[
            "in_stock",
            "back_order",
            "out_of_stock",
            "pre_order",
            "limited",
            "discontinued",
        ]
    ] = Field(
        None,
        description=(
            "Stock availability observed at a distributor, mapped from "
            "schema.org ItemAvailability. This is a per-seller, "
            "point-in-time snapshot — NOT an intrinsic product lead time "
            "(no honest public numeric lead time exists per part). Read it "
            "with availability_source_url + availability_fetched_at for "
            "provenance; it goes stale. Populated by availability-enrich."
        ),
    )
    availability_source_url: Optional[str] = Field(
        None,
        description="URL the availability status was scraped from.",
    )
    availability_fetched_at: Optional[str] = Field(
        None, description="ISO 8601 timestamp when availability was last fetched."
    )
    warranty: Optional[ValueUnit] = None
    lead_time: Optional[ValueUnit] = Field(
        None,
        description=(
            "Expected delivery / lead time for the product. Typically a "
            "ValueUnit with unit='days' (e.g. {'value': 30, 'unit': 'days'}). "
            "Sourced from manufacturer or distributor data, not the datasheet."
        ),
    )
    datasheet_url: Optional[str] = Field(
        None, description="URL of the source datasheet"
    )
    pages: Optional[list[int]] = Field(
        None,
        description="1-indexed PDF pages where this product's specs were found. Used for #page=N deep-linking.",
    )
